language: c

cache:
  directories:
    - nim

env:
  global:
    - REPONAME="$(basename ${TRAVIS_BUILD_DIR})" # /travis/build/kaushalmodi/hello_musl -> hello_musl
    - NIMREPO="https://github.com/nim-lang/Nim"
    - NIMVER="$(git ls-remote ${NIMREPO} devel | cut -f 1)"
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"

install:
  # - find /usr/include -name "*.h" -print
  - echo "NIMDIR = ${NIMDIR}"
  - |
    set -u # error on undefined variables
    set -e # exit on first error
    if [[ ! -f "${NIMDIR}/bin/nim" ]]
    then
      rm -rf nim
      mkdir -p nim
      git clone --single-branch --branch devel --depth=1 "${NIMREPO}" "${NIMDIR}"
      cd "${NIMDIR}" || exit
      sh build_all.sh
      # After building nim, wipe csources to save on cache space.
      rm -rf csources
    fi
  - export PATH="${NIMDIR}/bin:${PATH}"
  - nim -v

script:
  - echo "hello"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
