language: c
sudo: required

cache:
  directories:
    - nim
    - upx

addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools

install:
  - echo "Installing Nim devel .."
  # Build nim from its devel branch.
  # Check version of remote branch.
  - export NIMVER="$(git ls-remote https://github.com/nim-lang/Nim devel | cut -f 1)"
  # After building nim, wipe csources to save on cache space.
  - "{ [ -f nim/$NIMVER/bin/nim ] && [ -f nim/$NIMVER/bin/nimble ]; } ||
      { rm -rf nim;
        mkdir -p nim;
        git clone --single-branch --branch devel --depth=1 https://github.com/nim-lang/Nim nim/$NIMVER;
        cd nim/$NIMVER;
        sh build_all.sh;
        rm -rf csources;
        cd ../..;
      }"
  - export PATH="$PWD/nim/$NIMVER/bin:$PATH"
  # - export CHOOSENIM_NO_ANALYTICS=1
  # - export CHOOSENIM_CHOOSE_VERSION=devel
  # - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  # - sh init.sh -y
  # - export PATH=~/.nimble/bin:$PATH
  - nim -v

  - echo "Installing upx .."
  - export UPXVER="3.95"        # Change this value when upgrading upx
  - "{ [ -f upx/$UPXVER/upx ]; } ||
      { curl -OL https://github.com/upx/upx/releases/download/v${UPXVER}/upx-${UPXVER}-amd64_linux.tar.xz;
        tar xvf upx-${UPXVER}-amd64_linux.tar.xz;
        mkdir -p upx;
        mv upx-${UPXVER}-amd64_linux upx/${UPXVER};
      }"
  - export PATH="$PWD/upx/${UPXVER}/:$PATH"
  - upx --version | grep -E '^upx'

script:
  # Compile the static binary using musl.
  - nim musl src/hello_musl.nim
  # See that the binary is not dynamic.
  - ldd ./src/hello_musl || true
  # Run the binary.
  - ./src/hello_musl

branches:
  except:
    - gh-pages

before_deploy:
  - cp ./src/hello_musl .
  - tar caf hello_musl.Linux_64bit_musl.tar.xz hello_musl
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "hello_musl.Linux_64bit_musl.tar.xz"
  skip_cleanup: true
  on:
    tags: true

# References:
# choosenim: https://github.com/mratsim/Arraymancer/blob/master/.travis.yml
# musl: https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml
# nim build caching: https://github.com/status-im/nimbus/blob/master/.travis.yml
# https://docs.travis-ci.com/user/deployment/releases/
# https://github.com/nim-lang/Nim/wiki/TravisCI
